// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.WPF")>]
[<assembly: AssemblyProductAttribute("Elmish.WPF")>]
[<assembly: AssemblyDescriptionAttribute("F# bindings for using elmish in WPF")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.WPF"
    let [<Literal>] AssemblyProduct = "Elmish.WPF"
    let [<Literal>] AssemblyDescription = "F# bindings for using elmish in WPF"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
