name: Continuous Integration

on:
  push:
    branches: [ master, v3 ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install .NET SDKs
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Restore
      run: dotnet restore src/Elmish.WPF.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release src/Elmish.WPF.sln

    - name: Test
      run: dotnet test --no-build --configuration Release src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj

    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: "src/Elmish.WPF/Elmish.WPF.fsproj"
        PACKAGE_NAME: "Elmish.WPF"
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
